
name: 部署文档

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建页面
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 Pnpm 包管理器
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: 设置 Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 构建文档
        run: pnpm run docs:build

      - name: 上传构建
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: 部署页面
    steps:
      - name: 部署到 Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
